lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_id_claim: email
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:
            enabled: true
            name: BEARER
    set_cookies:
        'BEARER':
            httpOnly: true   # Permet d'ajouter HttpOnly
            secure: true      # Le cookie ne sera envoyé que via HTTPS
            samesite: 'none' # SameSite = None
            lifetime: 3600     # Expiration du cookie (en secondes)

