nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link', 'Set-Cookie']
        max_age: 3600
    paths:
        '^/api/': ~
        '^/api/': 
            allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE', 'PATCH']